apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vehium-docs-ingress
  namespace: bos
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/redirect.entryPoint: websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - docs.vehium.com
      secretName: vehium-docs-tls
  rules:
    - host: docs.vehium.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vehium-docs
                port:
                  number: 80
